# Site settings
title: Franco Talarico
email: francotalarico93@gmail.com
description: "Contenidos y consejos para realizar tus proyectos a un nivel profesional, con tecnologías modernas."
baseurl: ""
url: "http://francotalarico.me"
twitter_username: tala212
github_username:  francotalarico
facebook_username:  franco.talarico

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
